export default [
  {
    path: '/',
    redirect: 'login',
  },
  {
    path: '/login',
    component: '@/components/login',
  },
  {
    path: '/mock',
    component: '@/../mock/User',
  },
  {
    path: '/main',
    component: '@/layouts/index',
    routes: [
      {
        path: '/main',
        redirect: '/main/index',
      },
      {
        path: '/main/index',
        name: '首页',
        icon: 'HomeOutlined',
        component: '@/pages/index',
      },
      {
        path: '/main/system',
        name: '系统管理',
        icon: 'AppstoreOutlined',
        routes: [
          {
            path: '/main/system/organ',
            name: '组织管理',
            icon: 'AppstoreOutlined',
            routes: [
              {
                path: '/main/system/organ/userlist',
                name: '用户管理',
                icon: 'UserOutlined',
                component: '@/pages/admin/系统管理/组织管理/UserList',
                title: '用户管理',
              },
              {
                path: '/main/system/organ/useradd',
                component: '@/pages/admin/系统管理/组织管理/UserAdd',
                hideMenu: true,
                name: '新增用户',
                title: '新增用户',
              },
              {
                path: '/main/system/organ/useredit/:id',
                component: '@/pages/admin/系统管理/组织管理/UserEdit',
                hideMenu: true,
                name: '编辑用户',
                title: '编辑用户',
              },
              {
                path: '/main/system/organ/userfenpei',
                name: '用户分配角色',
                component: '@/pages/admin/系统管理/组织管理/UserFenPei',
                hideMenu: true,
                title: '用户分配角色',
              },
              {
                path: '/main/system/organ/usershuju',
                name: '用户分配数据权限',
                component: '@/pages/admin/系统管理/组织管理/UserShuJu',
                hideMenu: true,
                title: '用户分配数据权限',
              },
              {
                path: '/main/system/organ/organizelist',
                name: '机构管理',
                icon: 'AppstoreOutlined',
                component: '@/pages/admin/系统管理/组织管理/OrganizeList',
                title: '机构管理',
              },
              {
                path: '/main/system/organ/organizeadd',
                component: '@/pages/admin/系统管理/组织管理/OrganizeAdd',
                hideMenu: true,
                name: '新增机构',
                title: '新增机构',
              },
              {
                path: '/main/system/organ/Organizeedit/:id',
                component: '@/pages/admin/系统管理/组织管理/OrganizeAdd',
                hideMenu: true,
                name: '编辑机构',
                title: '编辑机构',
              },
              {
                path: '/main/system/organ/companylist',
                name: '公司管理',
                icon: 'FireOutlined',
                component: '@/pages/admin/系统管理/组织管理/CompanyList',
                title: '公司管理',
              },
              {
                path: '/main/system/organ/companyadd/',
                component: '@/pages/admin/系统管理/组织管理/CompanyAdd',
                hideMenu: true,
                name: '新增公司',
                title: '新增公司',
              },
              {
                path: '/main/system/organ/companyedit/:id',
                component: '@/pages/admin/系统管理/组织管理/CompanyAdd',
                hideMenu: true,
                name: '编辑公司',
                title: '编辑公司',
              },
              {
                path: '/main/system/organ/stationlist',
                name: '岗位管理',
                icon: 'TrophyOutlined',
                component: '@/pages/admin/系统管理/组织管理/StationList',
                title: '岗位管理',
              },
              {
                path: '/main/system/organ/stationadd',
                component: '@/pages/admin/系统管理/组织管理/StationAdd',
                hideMenu: true,
                name: '新增岗位',
                title: '新增岗位',
              },
              {
                path: '/main/system/organ/stationedit/:id',
                component: '@/pages/admin/系统管理/组织管理/StationAdd',
                hideMenu: true,
                name: '编辑岗位',
                title: '编辑岗位',
              },
            ],
          },
          {
            path: '/main/system/limit',
            name: '权限管理',
            icon: 'DropboxOutlined',
            routes: [
              {
                path: '/main/system/limit/rolelist',
                name: '角色管理',
                component: '@/pages/admin/系统管理/权限管理/RoleList',
                icon: 'TeamOutlined',
                title: '角色管理',
              },
              {
                path: '/main/system/limit/roleadd',
                name: '新增角色',
                component: '@/pages/admin/系统管理/权限管理/RoleAdd',
                title: '新增角色',
                hideMenu: true,
              },
              {
                path: '/main/system/limit/roleedit/:id',
                name: '编辑角色',
                component: '@/pages/admin/系统管理/权限管理/RoleAdd',
                title: '编辑角色',
                hideMenu: true,
              },
              {
                path: '/main/system/limit/roleMenu/:id',
                name: '授权菜单',
                component: '@/pages/admin/系统管理/权限管理/RoleMenu',
                title: '授权菜单',
                hideMenu: true,
              },
              {
                path: '/main/system/limit/secondlist',
                name: '二级管理员',
                component: '@/pages/admin/系统管理/权限管理/SecondList',
                icon: 'UserOutlined',
                title: '二级管理员',
              },
              {
                path: '/main/system/limit/secondadd',
                name: '新增二级管理员',
                component: '@/pages/admin/系统管理/权限管理/SecondAdd',
                title: '新增二级管理员',
                hideMenu: true,
              },
              {
                path: '/main/system/limit/systemlist',
                name: '系统管理员',
                component: '@/pages/admin/系统管理/权限管理/SystemList',
                icon: 'HomeOutlined',
                title: '系统管理员',
              },
              {
                path: '/main/system/limit/systemadd',
                name: '新增管理员',
                component: '@/pages/admin/系统管理/权限管理/SystemAdd',
                title: '新增管理员',
                hideMenu: true,
              },
            ],
          },
          {
            path: '/main/system/setting',
            name: '系统设置',
            icon: 'SettingOutlined',
            routes: [
              {
                path: '/main/system/setting/menulist',
                name: '菜单管理',
                component: '@/pages/admin/系统管理/系统设置/MenuList',
                icon: 'ReadOutlined',
                title: '菜单管理',
              },
              {
                path: '/main/system/setting/menuadd',
                component: '@/pages/admin/系统管理/系统设置/MenuAdd',
                hideMenu: true,
                name: '新增菜单',
                title: '新增菜单',
              },
              {
                path: '/main/system/setting/menuedit/:id',
                component: '@/pages/admin/系统管理/系统设置/MenuAdd',
                hideMenu: true,
                name: '编辑菜单',
                title: '编辑菜单',
              },
              {
                path: '/main/system/setting/modulelist',
                name: '模块管理',
                component: '@/pages/admin/系统管理/系统设置/ModuleList',
                icon: 'AppstoreOutlined',
                title: '模块管理',
              },
              {
                path: '/main/system/setting/moduleadd',
                name: '新增模块',
                component: '@/pages/admin/系统管理/系统设置/ModuleAdd',
                title: '新增模块',
                hideMenu: true,
              },
              {
                path: '/main/system/setting/parameterlist',
                name: '参数设置',
                component: '@/pages/admin/系统管理/系统设置/ParameterList',
                icon: 'ToolOutlined',
                title: '参数设置',
              },
              {
                path: '/main/system/setting/parameteradd',
                name: '新增参数',
                component: '@/pages/admin/系统管理/系统设置/ParameterAdd',
                title: '新增参数',
                hideMenu: true,
              },
              {
                path: '/main/system/setting/dictlist',
                name: '字典管理',
                component: '@/pages/admin/系统管理/系统设置/DictList',
                icon: 'DropboxOutlined',
                title: '字典管理',
              },
              {
                path: '/main/system/setting/dictadd',
                name: '新增字典类型',
                component: '@/pages/admin/系统管理/系统设置/DictAdd',
                title: '新增字典类型',
                hideMenu: true,
              },
              {
                path: '/main/system/setting/arealist',
                name: '行政区划',
                component: '@/pages/admin/系统管理/系统设置/AreaList',
                icon: 'BankOutlined',
                title: '行政区划',
              },
              {
                path: '/main/system/setting/areaadd',
                name: '新增区域',
                component: '@/pages/admin/系统管理/系统设置/AreaAdd',
                title: '新增区域',
                hideMenu: true,
              },
            ],
          },
          {
            path: '/main/system/monitor',
            name: '系统监控',
            icon: 'AlertOutlined',
            routes: [
              {
                path: '/main/system/monitor/loglist',
                name: '访问日志',
                component: '@/pages/admin/系统管理/系统监控/LogList',
                icon: 'BugOutlined',
                title: '访问日志',
              },
              {
                path: '/main/system/monitor/onlinelist',
                name: '在线用户',
                component: '@/pages/admin/系统管理/系统监控/OnlineList',
                icon: 'twitter',
                title: '在线用户',
              },
            ],
          },
        ],
      },
      {
        path: '/main/teshuzujian',
        name: '特殊组件',
        icon: 'AppstoreOutlined',
        routes: [
          {
            path: '/main/teshuzujian/xiangxingtu',
            name: '渐变象形图',
            icon: 'AlertOutlined',
            component: '@/pages/teshuzujian/jianbiantu',
          },
          {
            path: '/main/teshuzujian/map',
            name: '高德地图',
            icon: 'AlertOutlined',
            component: '@/pages/teshuzujian/map',
          },
        ],
      },
    ],
  }
];
